#19 horizontal resize
kirjs/ng2-codelab pull request #47
Opened 2016-12-11 19:14 UTC by UmaMoiseenko

Added component for horizontal resize.

<img width="1173" alt="screen shot 2016-12-11 at 2 12 54 pm" src="https://cloud.githubusercontent.com/assets/4104601/21082568/fc2fcad8-bfab-11e6-8666-50f2504c515b.png">
<img width="1206" alt="screen shot 2016-12-11 at 2 12 38 pm" src="https://cloud.githubusercontent.com/assets/4104601/21082570/fe9b36ae-bfab-11e6-85ba-182da310b1d1.png">

2016-12-12 03:21 UTC, kirjs requested changes

2016-12-12 03:21 UTC, kirjs commented on src/app/resize/resize.component.ts
> +	templateUrl: `
Curious why that works since below is not url. 
Please move out to an html file.

2016-12-12 03:21 UTC, kirjs commented on src/app/resize/resize.component.ts
> +	.handle {
Please move out to a CSS file.

2016-12-12 03:21 UTC, kirjs commented on src/app/resize/resize.component.ts
> +	constructor(private elRef: ElementRef) {}
elRef - never used?

2016-12-12 03:21 UTC, kirjs commented on src/app/resize/resize.component.ts
> +		'(mouseleave)': 'onMouseUp()'
nit, but seems confusing to call `onMouseUp` for mouseLeave, rename to `endDragging` maybe?

2016-12-12 03:21 UTC, kirjs commented on src/app/resize/resize.component.ts
> +		let w= this.initWidth + e.clientX -this.initOffsetX
Nit: rename to `width`

2016-12-12 03:21 UTC, kirjs commented on src/app/resize/resize.component.ts
> +		if (!this.isMouseDown) return
Nit: add curlies (`{`,`}`) to be consistent with the rest of the codebase

2016-12-12 03:21 UTC, kirjs commented on src/app/resize/resize.component.ts
> +
nit, but trying being more consistent with the spaces around operators, e.g. here:
* Space after `=`
* Space before `-`
* Spaces around `-`
Usually your IDE can do this for you if you reformat.

Same thing with semicolons, either have them everywhere or nowhere (for this codebase - everywhere). 

That's all is very minor, but way easier to read the code when it's consistent.

2016-12-12 03:21 UTC, kirjs commented on src/app/resize/resize.component.ts
> +		'(mousemove)': 'onMouseMove($event)',
What would be the benefit of listening this way as opposed to using @HostListener (I'm glad there's no github user with this name, haha)?

2016-12-12 03:21 UTC, kirjs commented on src/app/resize/resize.component.ts
> +	private isExpanded;
Is there any case when isExpanded would have a different value from isMouseDown? Can we get away with only using the latter?

2016-12-12 03:21 UTC, kirjs commented on src/app/resize/resize.component.ts
> +	.overlay {
this is pretty cool, but took me some time to understand, add a comment to explain the intent?

2016-12-12 03:21 UTC, kirjs commented on src/app/resize/resize.component.ts
> +		border-right: 1px dashed rgba(128, 128, 128, 0.5);
It feels a bit weird that handle in only on the right side of the line without any visual indication of that. 
Maybe add a nested div to get the border in the middle of the handle?

2016-12-12 03:21 UTC, kirjs commented on src/app/editors/editors.component.ts
> +  private editorWidth;
`editor` or `editors`?

2016-12-12 03:21 UTC, kirjs commented on src/app/resize/resize.component.ts
> +	private isExpanded;
I'm having a hard time understanding what get expanded is our case, could we find a better name for it? Or maybe I'm missing something?

2016-12-12 03:21 UTC, kirjs commented on src/app/resize/resize.component.ts
> +	selector: 'resize',
Add a prefix to the component name?
I've been using `app` so far in hopes that I'll rename it at some point. 
see https://angular.io/styleguide#!#02-07

2016-12-12 03:21 UTC, kirjs commented on src/app/editors/editors.component.html
> +  <resize [(width)]="editorWidth"></resize>
Do you think we could use content projection here?
This way we can access `app-editors` component using @ContentChild and measure/resize it from the resize component without modifying app-editors code at all.

https://scotch.io/tutorials/angular-2-transclusion-using-ng-content

2016-12-12 03:24 UTC, kirjs commented
Hi Uma, this actually looks pretty good, I added you a bunch of comments, most are pretty minor/code style. 

The main thing I would love to see here is moving out the remaining resizing bits from the app component (the last comment)

2016-12-12 04:03 UTC, UmaMoiseenko commented on src/app/resize/resize.component.ts
> +	selector: 'resize',
sounds good, will prefix with `app`for consistancy

2016-12-12 04:16 UTC, UmaMoiseenko commented on src/app/resize/resize.component.ts
> +		border-right: 1px dashed rgba(128, 128, 128, 0.5);
makes sense

2016-12-12 04:19 UTC, UmaMoiseenko commented on src/app/resize/resize.component.ts
> +		'(mousemove)': 'onMouseMove($event)',
:D I don't think there is a benefit, both work the same way afai

2016-12-12 04:20 UTC, UmaMoiseenko commented on src/app/resize/resize.component.ts
> +	private isExpanded;
you are right, removing isExpanded

2016-12-12 04:21 UTC, UmaMoiseenko commented on src/app/resize/resize.component.ts
> +	constructor(private elRef: ElementRef) {}
nope, went different rout at first. removing it!

2016-12-12 04:23 UTC, UmaMoiseenko commented on src/app/resize/resize.component.ts
> +
fair enough, will configure to keep code pretty

2016-12-12 04:24 UTC, UmaMoiseenko commented on src/app/editors/editors.component.ts
> +  private editorWidth;
`editors` make more sense I guess

2016-12-12 04:26 UTC, UmaMoiseenko commented on src/app/editors/editors.component.html
> +  <resize [(width)]="editorWidth"></resize>
Ok, I will look into that.

2016-12-12 04:30 UTC, UmaMoiseenko commented
@kirjs thanks for review! I'm all for consistency and clean code, so you made fair points.  I made most of the revisions, besides the transclusion part. Will try to find time during this week to finish it up.

2016-12-12 04:32 UTC, UmaMoiseenko commented
<img width="1100" alt="screen shot 2016-12-11 at 11 32 21 pm" src="https://cloud.githubusercontent.com/assets/4104601/21088097/22f3e566-bffa-11e6-8dd7-feffd7045d1f.png">

2016-12-12 04:35 UTC, kirjs commented
Sounds good, thanks for your work!

2016-12-14 04:30 UTC, UmaMoiseenko commented
@kirjs moved, let me know if it looks alright

2016-12-14 17:05 UTC, UmaMoiseenko commented
added some css to make main editors and `.side` elements take the full height

### before
![screen shot 2016-12-14 at 11 59 49 am](https://cloud.githubusercontent.com/assets/4104601/21192153/a0bfa4f6-c1f5-11e6-91d7-6fdeca953c9f.png)


### after
![screen shot 2016-12-14 at 11 58 38 am](https://cloud.githubusercontent.com/assets/4104601/21192159/a6136d70-c1f5-11e6-8c05-261347c00a09.png)

2016-12-15 09:19 UTC, kirjs commented on src/app/resize/resize.component.ts
> +		let w= this.initWidth + e.clientX -this.initOffsetX
also const?

2016-12-15 09:19 UTC, kirjs commented on src/app/resize/resize.component.css
> +	position: absolute;
I feel like `border-right` is the only property that actually affects anything, pretty sure you can get rid of the other five lines in `.handle` rule, since the parent component does centering for you. 

Alternatively just use `padding: 0 8px' in the parent component instead of using flex.

2016-12-15 09:19 UTC, kirjs commented on src/app/editors/editors.component.css
> +  padding-right: 1rem;
Nit: I've been using px values for padding everywhere else. 
Using rem sounds like a cool idea, but should be done across the app.

2016-12-15 09:19 UTC, kirjs commented on src/app/editors/editors.component.css
> +  box-sizing: border-box;
Nit: would it make sense to set the padding on the parent component instead of using box-sizing here?

2016-12-15 09:19 UTC, kirjs commented on src/app/resize/resize.component.css
> +	position: fixed;
Somehow all indentation became just 1 line. Please change to 2.

2016-12-15 09:19 UTC, kirjs commented on src/app/resize/resize.component.ts
> +		e.preventDefault();
why do we want to preventDefault if the mouse is not down?

2016-12-15 09:20 UTC, kirjs commented on src/app/resize/resize.component.css
> +.is-expanded {
still not sure what expanded means in this context.

2016-12-15 09:21 UTC, kirjs commented
I think it looks pretty good, left few minor comments.

2016-12-15 17:53 UTC, UmaMoiseenko commented on src/app/resize/resize.component.ts
> +		e.preventDefault();
it prevents text from highlighting when dragging cursor

2016-12-16 01:35 UTC, kirjs commented on src/app/resize/resize.component.ts
> +		e.preventDefault();
Yes, but do we care about it when the mouse is not down?

2016-12-16 01:41 UTC, kirjs approved these changes

2016-12-16 01:42 UTC, merged

2016-12-16 02:05 UTC, kirjs commented
Hi Uma, I'm merging this, because I really want to try it for the class I'm doing in a couple of hours. 

Thanks and great job on the component, I'll let you know how it goes :)

2016-12-16 21:47 UTC, UmaMoiseenko commented
@kirjs sounds good. I'll make a new branch to apply revisions